### ISSUE TITLE
How do I use JSBomb and does it work?

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#1]
Two questions. I was thinking of making a new account when 1 billion projects comes around and just spam JSBomb at like 999,999,700 and get the billionth project. So how do I use JSBomb and does it work?

Also, I think you can edit cookies to hack ppl on scratch

**Comment by S-PScripts** [comment]
At the bottom of the jsbomb.js there are instructions for how to get the xtoken and xcrsftoken

**Comment by ImmediateMurderProfessionals** [comment]
Okay. You should make a tutorial and post it to your YT or smth.

And I am assuming it works?

**Comment by S-PScripts** [comment]
> Okay. You should make a tutorial and post it to your YT or smth.
> 
> And I am assuming it works?

yes it still works

**Comment by S-PScripts** [comment]
hexagon is trying to dox you don't go to his website

**Comment by S-PScripts** [comment]
https://www.youtube.com/watch?v=WfUBUlEVJE8 wait 10 mins for this to process

**Comment by ImmediateMurderProfessionals** [comment]
He a.ready knows my ip he actually got banned from chess.com for posting my ip

**Comment by ImmediateMurderProfessionals** [comment]
It might also not work on my school pc because my school pc blocks inspect element for some reasom

**Comment by S-PScripts** [comment]
> It might also not work on my school pc because my school pc blocks inspect element for some reasom

if inspect element was unblocked you could find all sorts of ways to mess with your chromebook

**Comment by ImmediateMurderProfessionals** [comment]
Makes sense, also im on macbook not chromebook
