### ISSUE TITLE
Important as fuuuucccckkkkkkk

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#11]
Go to https://scratch.mit.edu/studios/5974533/comments and reply to the comment censoring my username and tell Hexagon that he can't do that because he's banned from HTS.

**Comment by ImmediateMurderProfessionals** [comment]
Tysm

**Comment by S-PScripts** [comment]
join discord

**Comment by ImmediateMurderProfessionals** [comment]
I dont have discord yet my parents are karens
