### ISSUE TITLE
That time Hexagon posted a death threat to Scratch

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#12]
<img width="959" alt="Death threat" src="https://github.com/S-PScripts/scripts/assets/156855194/bc83848b-ce6b-4084-8496-791b2ea68a92">

**Comment by ImmediateMurderProfessionals** [comment]
Why doesn't Hexagon move on from the doxxing bullshit

**Comment by S-PScripts** [comment]
is that you?
why would you leak your own location?
why did you say blue's location but it was yours?????

**Comment by ImmediateMurderProfessionals** [comment]
That's the image from the May 5th doxxing incident
