### ISSUE TITLE
Hexagon try not to be delusional challenge (Impossible)

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#13]
<img width="771" alt="Screenshot 2024-05-29 at 11 27 52 AM" src="https://github.com/S-PScripts/scripts/assets/156855194/0ac0dbae-14c0-4af0-b59d-dfab9d5c3d4c">
(From https://team-h-the-series.fandom.com/wiki/BombCraft)

For comparison, here's Minuit.
![phpcrigAT](https://github.com/S-PScripts/scripts/assets/156855194/7124b420-b6b4-4ba1-bb61-469a8a44b326)

And here's Im Glowing Insane.
![phpxscG11](https://github.com/S-PScripts/scripts/assets/156855194/e2c8dac1-99fc-4248-a473-e532cb2f38cc)

**Comment by S-PScripts** [comment]
minuit my ass 😭 
your level is so much better looking like if you kept improving on it, it could get featured
minuit looks like dodgy 1.6 dorabae ahh level

**Comment by S-PScripts** [comment]
> (It was because of one single comment where I said I wanted to glaze Split72’s fursona in a fine layer of my cum)

💀

**Comment by ImmediateMurderProfessionals** [comment]
One single comment should not warrant a comment ban for that long

**Comment by S-PScripts** [comment]
yeah

**Comment by ImmediateMurderProfessionals** [comment]
Yeah i hate the moderators
I also got a 13 day comment ban in march for posting a silly lil pickup line in daily chat (surprisingly Friday’s comment ban wasn’t about daily chat)
