### ISSUE TITLE
When is your last day of school

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#14]
My last day is June 4th.

**Comment by S-PScripts** [comment]
july 20th or something

**Comment by ImmediateMurderProfessionals** [comment]
Damn why so late

**Comment by S-PScripts** [comment]
> Damn why so late

**Comment by ImmediateMurderProfessionals** [comment]
We start school in the last week of august here in america, so it feels unfair that you get 1.5 months of summer vacation but in america we get 3 months

**Comment by S-PScripts** [comment]
breaks in uk:
1st half term (1w)
christmas (2w)
3rd half term (1w)
easter (2w)
5th half term (1w)
summer holiday (mid/late (15 - 22) july to early September (1st week)

more information:
https://en.wikipedia.org/wiki/English_school_holidays

**Comment by S-PScripts** [comment]
we have two more breaks than the US
ref: https://www.edarabia.com/school-holidays-united-states/

**Comment by ImmediateMurderProfessionals** [comment]
ok

**Comment by ImmediateMurderProfessionals** [comment]
> im a noob

This comment is edited. What did it originally say?

**Comment by S-PScripts** [comment]
it said "noob" (you can click edited to see the edit history)

**Comment by ImmediateMurderProfessionals** [comment]
ok

**Comment by trollfacenan** [comment]
[read me(中文).txt](https://github.com/user-attachments/files/15514379/read.me.txt)
