### ISSUE TITLE
Fun fact

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#22]
free my boy @bombcraft he aint do anything wrong. erm @bcmgf1137/19 you should unban @bombcraft from the studio NOW!!!! grrrrr ok i know he literally doxxed you and posted your address on gd and i know that he insulted the christians because he was atheist and i know that everything that he does causes drama and i know that he is constantly annoying you and 30is and i know that he has said despicable things about some h creators, but like,,,, idk man he was supposed to be unbanned june 21 :( pwease pwetty pwease @bcmgf1137/19 unban him or i will have to craft some bombs (funny pun) and drop them on youre house!!! dont make me angry... you wouldnt like me when im angry... grrrrrrrrrrrrrrrrrr... please @bcmgf1137/19 ignore literally all of the red flags and invite him back because he keeps spamming about how he wants to get unbanned!!!! you better do it right now or i'll..... uhh.............. uhhhhhhhhhhhhh.......... i will call you a meanie! ohoho yeah you wont like being called a meanie. i bet you would wet the bed upon me calling you a meanie huh all the more reason for you to unban @bombcraft tee hee :3 so unban him. now. succumb to his will. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. let him in. on an unrelated note: recognize these numbers? --> 102.532.431.923 hahahae nerd i will post the ip address again and you cant stop me. please *sob* *sob* im begging you... just unban bombcraft and ignore what he said about the christians... *wheese* im gonna die if you dont... dont let me die unless youre a monster, yeah you a monster if you dont unban @bombcraft from hts. 308 negra arroyo lane, albequerque new mexico. there, posted it. have fun putting that on h: announcements, nerd. and that, my friend, is why you should... UNBAN BOMBCRAFT

**Comment by S-PScripts** [comment]
wtf is wrong with you
