### ISSUE TITLE
Hexagon speedruns getting sued for defamation

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#23]
https://team-h-the-series.fandom.com/wiki/Special:MobileDiff/1309

**Comment by S-PScripts** [comment]
LOL kirkburn (fandom admin) reverted the changes 
hexagon didn't listen and reverted kirkburn's edits but kirkburn reverted again and sent to hexagon "stop that! we don't host attacks"

**Comment by ImmediateMurderProfessionals** [comment]
hexagon got a global block on fandom lmao
