### ISSUE TITLE
MY GD ACCOUNT GOT BANNED I WANT TO FUCKING KMS

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#25]
https://github.com/ImmediateMurderProfessionals/My-gd-account-is-banned-this-is-literally-1984/blob/main/read%20this

**Comment by S-PScripts** [comment]
oh

**Comment by ImmediateMurderProfessionals** [comment]
I'm not quitting GD because I will try to get my account unbanned

**Comment by ImmediateMurderProfessionals** [comment]
Shouldn't be that hard to get un-cancelled, right?
