### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#28]
so
it turns out i was never banned from gd
the shitty anti-bot thought i was a bot
and deleted my levels and comments
and reset my password
this whole fucking time i couldve just did forgot password
and i only figured it out earlier today
lmao
also
i start high school on the 26th
also also 
i'm on discord now (@BombCraft on discord)

**Comment by S-PScripts** [comment]
> so it turns out i was never banned from gd the shitty anti-bot thought i was a bot and deleted my levels and comments and reset my password this whole fucking time i couldve just did forgot password and i only figured it out earlier today lmao also i start high school on the 26th also also i'm on discord now (@BombCraft on discord)

maybe it was because you were shitposting so many levels
tbh though RIP to the levels you did lots of effort in

**Comment by ImmediateMurderProfessionals** [comment]
LDM ball cube ball big cube ball next Rest In Peace niflheim vismuth slow wave fast robot keep going! slow ship go! slow ball Auto? fast dual ship slow fast ufo slow How? fast ship slow cube fast ball lol slow robot in out slow ufo take a break ????? !!!!! ?? ?! ??! !! ?! !! ?!!? ??! !! ?!!? ??! ?! ?? !! ?? !! ?? ?! ??! ?!!? ?? ??! ?! !! ?!!? slow ufo go! go! Yeah! fast cube dual wave watch out! faster! OMG! mini next next great! verified by NIFLHEIM koreaqwer

**Comment by S-PScripts** [comment]
huh

**Comment by trollfacenan** [comment]
I have implanted bitcoin miners to all of your computers 😈

**Comment by S-PScripts** [comment]
wjat
