### ISSUE TITLE
Gd cologne blocked me on github wtf

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#3]
title

**Comment by S-PScripts** [comment]
REAL?!?!?!!!

**Comment by ImmediateMurderProfessionals** [comment]
Yes, GD Cologne blocked me on github

**Comment by ImmediateMurderProfessionals** [comment]
(The comment I posted that was deleted read "r/skamtebord")

**Comment by ImmediateMurderProfessionals** [comment]
but he blocked me because i posted this
<img width="1440" alt="Screen Shot 2024-03-18 at 8 38 21 AM" src="https://github.com/S-PScripts/scripts/assets/156855194/d981ffc3-1b01-4c7e-a9d2-8f9b9724b331">
