### ISSUE TITLE
I can still see the jsbomb in the commit history

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#5]
Add your description here...

**Comment by ImmediateMurderProfessionals** [comment]
I think you can see the jsbomb in the history never checked tho

**Comment by S-PScripts** [comment]
Sorry for the late reply, I was at some camping shit.

I know the JSBOMB can still be found but I don't fcking care, most people won't bother to find it.

**Comment by onezpp** [comment]
https://en.wikipedia.org/wiki/Streisand_effect

**Comment by S-PScripts** [comment]
> https://en.wikipedia.org/wiki/Streisand_effect

Why did you have to have the need to comment that?

**Comment by S-PScripts** [comment]
i re added it anyways since idc about what ppl use it for

**Comment by ImmediateMurderProfessionals** [comment]
ok
