### ISSUE TITLE
found this comment on h3447 smh

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [S-PScripts/scripts#8]
<img width="667" alt="Whisper down the alley" src="https://github.com/S-PScripts/scripts/assets/156855194/a1f0e602-9f4b-457c-ae99-3781bcdad58c">

**Comment by S-PScripts** [comment]
bruh aleph probably got his facts from blue or something you've never doxxed me LOL

**Comment by ImmediateMurderProfessionals** [comment]
Ye my guess is that he thought that the (later proven to be false) accusations of you doxxing blue were me doxxing you. Also, that's Aleph?

**Comment by S-PScripts** [comment]
Yes, it's aleph (fishbowl)
